### ISSUE TITLE
Continue Bug

### ISSUE THREAD

**Issue by us09alex** [kylecoburn/secret-hitler#10]
Hey,

I can't press the continue button at the start of the round in google chrome. At the moment I must press the button in the right bottom corner to play the round. I think the cards which show your role blocks the button.

**Comment by thaiduynguyen** [comment]
Just zoom out. It makes all the elements of the webpage smaller so it fits better.

**Comment by kylecoburn** [comment]
Thanks for the report, right now the game requires an arbitrary minimum window size. Not ideal, but I haven't had time to design a smaller one, or one for mobile. Zooming out is a good suggestion; you can also try taking the browser window fullscreen.

For the moment I've removed the role/party cards from the start display as a partial fix.
