### ISSUE TITLE
Block President's and Chancellor's Chat and Mic When In Process of Policy Enactment

### ISSUE THREAD

**Issue by thaiduynguyen** [kylecoburn/secret-hitler#12]
According to the rules, "The sanctity of the legislative session is of the utmost importance! Once it begins with the President drawing three Policy cards, the members of the government should be silent until a policy has been enacted". I suggests you prevent the president and chancellor from messaging or speaking (the voice chat works fine for me and some others btw) during policy enactment. Also, dead players shouldn't be able to speak either.

**Comment by 4311021x** [comment]
I don't think dead players should be muted. I think it is not against the rules of the tabletop game and the dead player has no advantage when he is dead. It would just make it more boring.

**Comment by thaiduynguyen** [comment]
"If the executed player is not Hitler, he does not reveal his role or his loyalty. He is removed from the game and may not speak, vote, or run for office." 
Straight from the rule book, mate.

**Comment by kylecoburn** [comment]
Thanks for the report, this should be fixed now during policies and for killed players until the game ends.

**Comment by thaiduynguyen** [comment]
The text chat is muted but the voice chat isn't.
