### ISSUE TITLE
Nein card blocks lower right player

### ISSUE THREAD

**Issue by MathSquared** [kylecoburn/secret-hitler#17]
In some layouts, the "Nein" voting card blocks the name of the player in the lower right of the main play screen.
![blocked-sh-p6](https://cloud.githubusercontent.com/assets/7842810/14765232/9b6bf5a0-099e-11e6-813f-d1c651b6fee8.png)

**Comment by kylecoburn** [comment]
Thanks for the report. I changed the layout system for the cards; they're now centered over the game window.
