### ISSUE TITLE
Chat auto scrolls to bottom

### ISSUE THREAD

**Issue by MathSquared** [kylecoburn/secret-hitler#18]
When scrolling up in chat, the chat jumps back down if a new message appears. This is annoying UX if people are trying to read back in chat.

**Comment by thaiduynguyen** [comment]
This have been brought in another thread [here](https://github.com/kylecoburn/secret-hitler/issues/11).

**Comment by MathSquared** [comment]
Duplicate of #11 as @thaiduynguyen pointed out. Apologies.
