### ISSUE TITLE
Permit scrolling on game selection and waiting for players screens

### ISSUE THREAD

**Issue by MathSquared** [kylecoburn/secret-hitler#21]
When there are too many games being formed, it's impossible to scroll down to view the ones later on the list. Similarly, on small monitors (1366x768) you can't see the last two players on the waiting for players screen. Maybe add an `overflow-y: scroll` to the page only on the game selection and waiting for players screens?

**Comment by kylecoburn** [comment]
Thanks for the report. Enabled scrolling in the lobby and added padding to the player list which should prevent it scrolling under the chat bar.
