### ISSUE TITLE
Guest Mode Feedback

### ISSUE THREAD

**Issue by ryantheleach** [kylecoburn/secret-hitler#4]
Cheers kyle with the help earlier, tried playing this with my mates to see how it faired.

one issue we had was clicking guest / using email addresses, it would be really handy to still specify a username for guests, otherwise we are all guest1 guest2 etc and can't work out who is who.

Additionally when trying to swap out of guest mode and register, it wasn't possible to swap without creating an incognito tab, someone tried clearing cookies but it may have been user error, I'm not sure.

**Comment by kylecoburn** [comment]
Appreciate your playtesting suggestions! I'd forgotten about adding sign out button.

Guests are intended more for testing purposes, given the beta state of the game, and may be removed in the future, so I don't plan to add more features to them (name changing, etc.).
