### ISSUE TITLE
Chancellor seems to be broken on firefox.

### ISSUE THREAD

**Issue by ryantheleach** [kylecoburn/secret-hitler#6]
http://puu.sh/nnkz8/2b2d2d4518.jpg

**Comment by ryantheleach** [comment]
Actually it becomes unclickable on chrome intermittently as well

**Comment by kylecoburn** [comment]
This is actually caused by inconsistent game state tracking on the server vs client, so the browser isn't responsible.

I fixed one known instance, but please let me know if you see this in any future games (try to note the action that just occurred prior to it getting stuck, if possible). Thanks!
