### ISSUE TITLE
DB Schema Not Provided

### ISSUE THREAD

**Issue by Pezmc** [kylecoburn/secret-hitler#7]
Hey Kyle,

This looks pretty sweet, we hit the bug in #6 when trying to test it and I wanted to try and track down the issue and commit a fix, _but_ it seems like we need the database schema in order to run the server locally and this isn't committed. I could deduce this from the code, but it might be easier to just have a copy!

Would you consider dumping the structure and sharing it?

**Comment by kylecoburn** [comment]
Thanks for pointing this out. I intended to make it runnable without a db for testing (for most debug purposes there isn't any need for the db).

I've now updated the guest system to work without it. There are still some limitations, so let me know if this is insufficient for your needs testing any gameplay aspects.
