### ISSUE TITLE
The inactivity warning is bugged

### ISSUE THREAD

**Issue by thaiduynguyen** [kylecoburn/secret-hitler#9]
I don't know when the warning should pops up but I don't think its suppose to pops up every second. I can't wait for other players because it keeps kicking me back to the main page. Sometime the warning pops up immediately after pressing 'Quickplay' and sometimes it pops up when typing in chat. It's very annoying and it's preventing me and others from playing the game.

**Comment by kylecoburn** [comment]
Thanks for the report, these issues around the timeouts triggering incorrectly should be fixed now.
